# Generated by Django 4.0.1 on 2022-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_producttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
